### ISSUE TITLE
[REGRESSION] 0.4.8 has a regression

### ISSUE THREAD

**Issue by rraina** [christsim/multicoin-address-validator#26]
This snippet used to return `false`. 
```
WAValidator.validate('bc1ql08eyrk03qytqc5pdp5fnwpfh0x3y3k2skauvd', 'bch')
```

However, now breaks completely
```
Uncaught TypeError: Cannot read property 'prod' of undefined
    at Object.isValidAddress (../node_modules/multicoin-address-validator/src/crypto/segwit_addr.js:89:47)
    at Object.isValidAddress (.../node_modules/multicoin-address-validator/src/bitcoin_validator.js:84:78)
    at Object.isValidAddress (.../node_modules/multicoin-address-validator/src/bch_validator.js:46:80)
    at Object.validate (.../node_modules/multicoin-address-validator/src/wallet_address_validator.js:14:39)
```

cc: @christsim

**Comment by christsim** [comment]
Is this still a problem?  Please reopen if it is.
